### ISSUE TITLE
How to change baud rate?

### ISSUE THREAD

**Issue by jeffallen** [CircuitMess/Chatter#3]
Hello,

I was not able to upload programs to my chatter with the default settings. But with baud rate 115200, it works.

I see that the baud rate is set here:
https://github.com/CircuitMess/Arduino-ESP32/blob/cb017c8535efb4254a043b3ef5144783302845e3/boards.txt#L351

How can I modify that?

**Comment by MiLeG** [comment]
Hey Jeff, 

We'll make sure to add the baud rate options in our platform files, we just didn't have any issues with the old 921600 baud rate up until now.
I have suggested these changes and they are now waiting for review (@filipbudisa)

BTW, the repository with platform files for our boards is [here](https://github.com/CircuitMess/Arduino-ESP32)

Thanks for bringing this to our attention!

**Comment by jeffallen** [comment]
Any idea why my Chatter is set to 115200? I wonder if I can change that instead?

**Comment by MiLeG** [comment]
To change the baud rate manually you can edit the boards.txt file located in:

C:\Users\<username>\AppData\Local\Arduino15\packages\cm\hardware\esp32\1.5.0\ for Windows, or
~/.arduino15/packages/cm/hardware/esp32/1.5.0/boards.txt for Linux/OSX machines.

Then, scroll down to the Chatter board definition and edit these lines

```
chatter.menu.UploadSpeed.921600=921600
chatter.menu.UploadSpeed.921600.upload.speed=921600
```

to look like this:

```
chatter.menu.UploadSpeed.115200=115200
chatter.menu.UploadSpeed.115200.upload.speed=115200
```

Now restart Arduino IDE and the baud rate should be changed.

The higher your baud rate the more unstable, but faster the data transfer will be.
For example, an unstable power supply or a low-quality or too long USB cable would usually cause this.

Hope this helps!
